services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

