services:
  frontend:
    build: ./frontend
    expose:
      - "80"

  backend:
    build: ./backend
    expose:
      - "8000"
    depends_on:
      - mongo 
    env_file:
      - .env
    volumes:
      - ${EMBEDDINGS_DIR}:/app/embeddings

  mongo:
    image: mongo
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    
  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
