name: Deploy via SSH

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            # Create directory if not exists
            mkdir -p ~/app
            cd ~/app

            # If repo already exists, pull; else, clone
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/Martin187187/LLMInjectorDemo . --branch main
            fi

            # Run docker-compose
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          EOF

